/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'toan' at '7/25/16 2:37 PM' with Gradle 2.13
 *
 * @author toan, @date 7/25/16 2:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
